### ISSUE TITLE
turisticka zajednica

### ISSUE THREAD

**Issue by jalmasi** [the-shop/troskovi-tvrtke#5]
... je mjesecni trosak. Ne znam da li vazi za cijelu rvacku, ali znam da placam TZ svaki mjesec, iako se ne bavim nicime sto ima veze sa turizmom.

**Comment by lotar** [comment]
Ugostiteljska djelatnost?

**Comment by jalmasi** [comment]
Nope, informatika, zagreb.

**Comment by lotar** [comment]
Ovisi kako si registriran, samo na primarnu djelatnost se plaća (pitao računovodstvo upravo) -  http://narodne-novine.nn.hr/clanci/sluzbeni/2008_12_152_4143.html

**Comment by jalmasi** [comment]
Hej, znam da je placam, a bogami znam i ljude koje su blokirali zbog neplacanja (rade softver).
Pazi, u zakonu nigdje eksplicitno ne pise primarna djelatnost...

**Comment by lotar** [comment]
Dodano
