### ISSUE TITLE
porez na ime tvrtke odlazi u povijest

### ISSUE THREAD

**Issue by jakovd** [the-shop/troskovi-tvrtke#7]
od 1.1.2017 više se ne plaća ova glupost

**Comment by lotar** [comment]
S obzirom da nisam vidio sluzbeno da je ukinuto ostavio sam napomenu - https://github.com/the-shop/troskovi-tvrtke/commit/8934d15045e9d4bc98965ed80c5a83724d13e302

hvala!

**Comment by lotar** [comment]
Maknuto ipak, potvrdio sa knjigovodstvom. https://github.com/the-shop/troskovi-tvrtke/commit/3f269fc4e655a09435b500763330c2830edf4718
